version: "3.9"

services:
  ui:
    image: internal-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_IDENTITY_SERVICE_BASE_URL=http://localhost:1000
        - VITE_USER_SERVICE_BASE_URL=http://localhost:1001
        - VITE_CATALOG_SERVICE_BASE_URL=http://localhost:1002
        - VITE_LOGIN_UI_BASE_URL=http://localhost:2000
    container_name: internal-ui
    ports:
      - 2002:80
    restart: on-failure
